server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location ~* \.(?:css|js)$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location ~* \.(?:mp4|webm|ogg)$ {
        mp4;
        mp4_buffer_size 1m;
        mp4_max_buffer_size 10m;
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }

    location ~* \.(?:apk)$ {
        add_header Content-Disposition 'attachment; filename="AlgoVirtual.apk"';
        expires 30d;
        access_log off;
    }

    location ~* \.(?:ico|gif|jpe?g|png|woff2?|eot|ttf|otf|svg|pdf)$ {
        expires 7d;
        access_log off;
        add_header Cache-Control "public";
    }
}
